modLoader = "javafml"
loaderVersion = "[${forge_loader_version},)"
license = "${mod_license}"

[[mods]]
modId = "battlecorrection"
version = "${version}"
displayName = "${mod_name}"
logoFile = "logo.png"
authors = "${mod_author}"
credits = "特别感谢 建议重开 为本项目提供的支持和帮助"
description = '''
战斗修正模组，提供各种
RPG 战斗增强功能
'''

[[dependencies.battlecorrection]]
modId = "forge"
mandatory = true
versionRange = "[${forge_loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.battlecorrection]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"